spring.application.name=knowledge
docs.path=/home/ilya/IdeaProjects/knowledge-docs/docs/
weaviate.collection.name=urfuKnowledge
ollama.api-endpoint=http://ollama:11434
ollama.vector-model=nomic-embed-text
server.port=8081